definitions
def0d9848bd7f3648a6aa0a7b52ca2552fd
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#copyOf->#'3866fa6c-f51b-42ab-8ff0-67282c55f7b1'); add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'10 July 2015 7:33:09 pm'); yourself)); add: (#id->#'0d9848bd-7f36-48a6-aa0a-7b52ca2552fd'); add: (#block->[:in :out | in ifNotEmpty: [out add: [#'f99d4fd1-3d69-436f-8e2b-e897e450b2f8'] value]]); add: (#sourceCode->'[:in :out | in ifNotEmpty: [out add: [#''f99d4fd1-3d69-436f-8e2b-e897e450b2f8''] value]]'); yourself)