definitions
def3866fa6cf51b42ab8ff067282c55f7b1
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'9 July 2015 3:03:16 am'); yourself)); add: (#id->#'3866fa6c-f51b-42ab-8ff0-67282c55f7b1'); add: (#block->[:in :out | in ifNotEmpty: [out add: [#'f99d4fd1-3d69-436f-8e2b-e897e450b2f8'] value]]); add: (#sourceCode->'[:in :out | in ifNotEmpty: [out add: [#''f99d4fd1-3d69-436f-8e2b-e897e450b2f8''] value]]'); yourself)