definitions
def4cd61f7fe47b48afb56635d05b819806
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'10 July 2015 7:34:45 pm'); yourself)); add: (#id->#'4cd61f7f-e47b-48af-b566-35d05b819806'); add: (#block->[:in :out | out add: {#objects -> in}, [{
	#bounds -> (1@0 corner: 427@397).
	#current -> #'942ba1de-1098-4cb4-8300-43e117f95666'.
	#id -> #'3770640e-e2df-4628-98bb-66612873bb69'.
	#out -> #(#(#interactive #'36243f2b-ee57-4691-8fa1-cc6d867e3f10' ) #(#interactive #'6e86ed4c-9dfa-4314-862b-b54c599271ca' ) ).
	#in -> #(#(#automatic #outer ) ).
}] value]); add: (#sourceCode->'[:in :out | out add: {#objects -> in}, [{
	#bounds -> (1@0 corner: 427@397).
	#current -> #''942ba1de-1098-4cb4-8300-43e117f95666''.
	#id -> #''3770640e-e2df-4628-98bb-66612873bb69''.
	#out -> #(#(#interactive #''36243f2b-ee57-4691-8fa1-cc6d867e3f10'' ) #(#interactive #''6e86ed4c-9dfa-4314-862b-b54c599271ca'' ) ).
	#in -> #(#(#automatic #outer ) ).
}] value]'); yourself)