definitions
def4cd61f7fe47b48afb56635d05b819806
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'10 July 2015 7:34:45 pm'); yourself)); add: (#id->#'4cd61f7f-e47b-48af-b566-35d05b819806'); add: (#block->[:in :out | out add: {#objects -> in}, [{
	#bounds -> (345@0 corner: 763@85).
	#current -> #'c3039d39-2510-4152-9c9c-2063276b026b'.
	#id -> #'36243f2b-ee57-4691-8fa1-cc6d867e3f10'.
	#out -> #().
	#in -> #(#(#interactive #'3770640e-e2df-4628-98bb-66612873bb69' ) ).
}] value]); add: (#sourceCode->'[:in :out | out add: {#objects -> in}, [{
	#bounds -> (345@0 corner: 763@85).
	#current -> #''c3039d39-2510-4152-9c9c-2063276b026b''.
	#id -> #''36243f2b-ee57-4691-8fa1-cc6d867e3f10''.
	#out -> #().
	#in -> #(#(#interactive #''3770640e-e2df-4628-98bb-66612873bb69'' ) ).
}] value]'); yourself)