definitions
def8142470173824a7f9646793417d10ba4
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'10 July 2015 7:34:01 pm'); yourself)); add: (#id->#'81424701-7382-4a7f-9646-793417d10ba4'); add: (#block->[:in :out | out add: {#objects -> in}, [{
	#bounds -> (432@0 corner: 929@71).
	#current -> #'c3039d39-2510-4152-9c9c-2063276b026b'.
	#id -> #'36243f2b-ee57-4691-8fa1-cc6d867e3f10'.
	#out -> #().
	#in -> #(#(#interactive #'3770640e-e2df-4628-98bb-66612873bb69' ) ).
}] value]); add: (#sourceCode->'[:in :out | out add: {#objects -> in}, [{
	#bounds -> (432@0 corner: 929@71).
	#current -> #''c3039d39-2510-4152-9c9c-2063276b026b''.
	#id -> #''36243f2b-ee57-4691-8fa1-cc6d867e3f10''.
	#out -> #().
	#in -> #(#(#interactive #''3770640e-e2df-4628-98bb-66612873bb69'' ) ).
}] value]'); yourself)