definitions
deff155b5ff6526480eb9ba9ab54a45f662
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'9 July 2015 1:16:43 am'); yourself)); add: (#id->#'f155b5ff-6526-480e-b9ba-9ab54a45f662'); add: (#block->[:in :out | in
		do: [:obj | (out identityIncludes: obj)
				ifFalse: [out add: obj]]]); add: (#sourceCode->'[:in :out | in
		do: [:obj | (out identityIncludes: obj)
				ifFalse: [out add: obj]]]'); yourself)