steps
stepsnippets
	<step>

	^ ((Dictionary new) add: (#definition->#'9c92fb55-0f53-44c8-9b39-552194fe0067'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->Object); add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'9 July 2015 1:16:43 am'); add: (#outputKind->ViQuerySnippetDefinition); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#snippets); add: (#isReference->false); add: (#viewDefinition->nil); yourself)