steps
step047ec1c825784b3f8a993d2670fd42ec
	<step>

	^ ((Dictionary new) add: (#definition->#'ef3265e1-668d-494c-bef6-181d0b4478d3'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'10 July 2015 7:34:01 pm'); add: (#copyOf->#'f4c63ac0-a7ff-4da5-bee2-e3429a6bebc3'); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->#'06f4ea1c-1038-48a6-bacf-14a7b3a4ee01'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'047ec1c8-2578-4b3f-8a99-3d2670fd42ec'); add: (#isReference->false); add: (#viewDefinition->nil); yourself)