steps
stepgroups
	<step>

	^ ((Dictionary new) add: (#definition->#'c32f87c6-1c09-46e7-8d62-a12f4f0badf1'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->#(nil nil )); add: (#creationTimeStamp->'9 July 2015 1:16:43 am'); add: (#view->ViTreeView); add: (#creationAuthor->'cc'); yourself)); add: (#isProperty->false); add: (#next->#'bf497c9e-7892-4e34-a327-d75650fdf5d3'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#groups); add: (#isReference->false); add: (#viewDefinition->nil); yourself)