steps
stepobjectExplorer
	<step>

	^ ((Dictionary new) add: (#definition->#'6884f134-f01f-4845-910a-034c73ce383b'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#priority->500); add: (#view->ViExplorerView); add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'9 July 2015 1:16:43 am'); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->'Inspector'); add: (#iconCode->'nil'); add: (#id->#objectExplorer); add: (#isReference->false); add: (#viewDefinition->nil); yourself)