steps
stepb0a7189cdf474775802e247f2e3775a5
	<step>

	^ ((Dictionary new) add: (#definition->#'e537bf70-d7b7-4a25-b165-c08cdfb3a77e'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'10 July 2015 7:33:09 pm'); add: (#copyOf->#'3ec57f85-c3f0-4ae9-8809-8352569e3745'); add: (#isNew->false); yourself)); add: (#isProperty->true); add: (#next->#'b5752cd9-ddb5-4a5a-bfd2-2d96b61fdeb7'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'b0a7189c-df47-4775-802e-247f2e3775a5'); add: (#isReference->false); add: (#viewDefinition->nil); yourself)