steps
step09a705508f7540a191f8f76f6f74c232
	<step>

	^ ((Dictionary new) add: (#definition->#'8c967a08-bfa2-4d14-b5a1-98b165cfed4c'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputType->MailArchiveEntry); add: (#view->ViTextView); add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'9 July 2015 3:21:19 am'); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->#'f4c63ac0-a7ff-4da5-bee2-e3429a6bebc3'); add: (#label->'Message'); add: (#iconCode->'nil'); add: (#id->#'09a70550-8f75-40a1-91f8-f76f6f74c232'); add: (#isReference->false); add: (#viewDefinition->nil); yourself)