steps
step9de447b3fe9b46208ab5488f6cf9f89e
	<step>

	^ ((Dictionary new) add: (#definition->#'f84cec3f-6e85-42a3-a620-a4fa06502b45'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'9 July 2015 2:59:18 am'); yourself)); add: (#isProperty->false); add: (#next->#'d7e7ba99-708d-4a6e-9433-0d129aeff1e8'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'9de447b3-fe9b-4620-8ab5-488f6cf9f89e'); add: (#isReference->false); add: (#viewDefinition->nil); yourself)