steps
stepff6e51e8bc1b46f5a080851208e69747
	<step>

	^ ((Dictionary new) add: (#definition->#'4dbf1795-b792-4f92-9708-72fcb74b96c9'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'9 July 2015 1:16:43 am'); yourself)); add: (#isProperty->false); add: (#next->#'d27aa744-d9a1-4cdb-8ef5-6d73fe818621'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'ff6e51e8-bc1b-46f5-a080-851208e69747'); add: (#isReference->false); add: (#viewDefinition->nil); yourself)