steps
stepd08073e6656449efab2ef62d10e57cc1
	<step>

	^ ((Dictionary new) add: (#definition->#'e32648c3-9407-4b08-9ba7-6efd638e53da'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'10 July 2015 7:34:40 pm'); add: (#copyOf->#'c1bcb105-6b34-434d-ac0a-29f5c97c9991'); add: (#isNew->false); yourself)); add: (#isProperty->true); add: (#next->#'f4830bc7-1e6e-4761-b74c-4f8069f57611'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'d08073e6-6564-49ef-ab2e-f62d10e57cc1'); add: (#isReference->false); add: (#viewDefinition->nil); yourself)