steps
step5e47068e80904506b98a3fe787062073
	<step>

	^ ((Dictionary new) add: (#definition->#'5dab782e-aa7a-4d32-88cb-6b2be3ebd1f2'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'9 July 2015 1:16:43 am'); yourself)); add: (#isProperty->true); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'5e47068e-8090-4506-b98a-3fe787062073'); add: (#isReference->false); add: (#viewDefinition->nil); yourself)