steps
stepimplementors
	<step>

	^ ((Dictionary new) add: (#definition->#'4f2ddbeb-ecd1-4134-b34a-08427d811302'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->ByteSymbol); add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'9 July 2015 1:16:43 am'); add: (#outputKind->MethodReference); add: (#priority->200); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->'Implementors'); add: (#iconCode->'nil'); add: (#id->#implementors); add: (#isReference->false); add: (#viewDefinition->nil); yourself)