steps
step81782998a7a442a082000c995d811e2f
	<step>

	^ ((Dictionary new) add: (#definition->#'8ee9f1fe-9918-40ed-bcd3-f459a35fd317'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'10 July 2015 7:33:09 pm'); add: (#copyOf->#'ee67a9b0-655e-46a5-a29f-b524f1478328'); add: (#isNew->false); yourself)); add: (#isProperty->true); add: (#next->#'83d4711f-0e2a-4b22-8598-78572003dc6b'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'81782998-a7a4-42a0-8200-0c995d811e2f'); add: (#isReference->false); add: (#viewDefinition->nil); yourself)