steps
stepd7e7ba99708d4a6e94330d129aeff1e8
	<step>

	^ ((Dictionary new) add: (#definition->#'3866fa6c-f51b-42ab-8ff0-67282c55f7b1'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'9 July 2015 3:03:16 am'); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'d7e7ba99-708d-4a6e-9433-0d129aeff1e8'); add: (#isReference->true); add: (#viewDefinition->nil); yourself)