steps
stepbc0000b3bcd14dc69bd7a342421895f9
	<step>

	^ ((Dictionary new) add: (#definition->#'a33606f0-dcb1-46bf-80fe-fd69e2aef97e'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'9 July 2015 3:45:05 am'); yourself)); add: (#isProperty->true); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'bc0000b3-bcd1-4dc6-9bd7-a342421895f9'); add: (#isReference->false); add: (#viewDefinition->nil); yourself)