steps
stepc4dde50841f34be4aa106b3535c7d4e4
	<step>

	^ ((Dictionary new) add: (#definition->#'1c54dd27-9d02-4824-9322-bc9d7a83c23d'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'9 July 2015 1:16:43 am'); yourself)); add: (#isProperty->false); add: (#next->#'1de79403-5bd2-405b-877d-97a5f88bb7a6'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'c4dde508-41f3-4be4-aa10-6b3535c7d4e4'); add: (#isReference->false); add: (#viewDefinition->nil); yourself)