steps
stepe88502ff0f4e4238b24206630d4113fe
	<step>

	^ ((Dictionary new) add: (#definition->#'0d9848bd-7f36-48a6-aa0a-7b52ca2552fd'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'10 July 2015 7:33:09 pm'); add: (#copyOf->#'d7e7ba99-708d-4a6e-9433-0d129aeff1e8'); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'e88502ff-0f4e-4238-b242-06630d4113fe'); add: (#isReference->true); add: (#viewDefinition->nil); yourself)