steps
stepd27aa744d9a14cdb8ef56d73fe818621
	<step>

	^ ((Dictionary new) add: (#definition->#'8775c4ee-e78b-40fc-93d5-de0987c1e6ba'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'9 July 2015 1:16:43 am'); yourself)); add: (#isProperty->false); add: (#next->#'c1d85e7c-8bf4-46af-a27a-1bcce4246347'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'d27aa744-d9a1-4cdb-8ef5-6d73fe818621'); add: (#isReference->false); add: (#viewDefinition->nil); yourself)