steps
stepad47d780cb6542e58cdf17110bdc4f09
	<step>

	^ ((Dictionary new) add: (#definition->#'50a4601d-1bc0-4af4-845c-73751361fb9c'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->MailArchive); add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'9 July 2015 2:01 am'); add: (#view->ViTreeViewExtended); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->#'3ec57f85-c3f0-4ae9-8809-8352569e3745'); add: (#label->'Inboxes'); add: (#iconCode->'nil'); add: (#id->#'ad47d780-cb65-42e5-8cdf-17110bdc4f09'); add: (#isReference->false); add: (#viewDefinition->nil); yourself)