steps
step78daa25df9024123993c80d30787981f
	<step>

	^ ((Dictionary new) add: (#definition->#'b0b8220b-51ea-4ea8-8195-26c2a9181ae1'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->MailArchiveEntry); add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'10 July 2015 10:13:31 am'); add: (#view->ViTableView); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->#'c1bcb105-6b34-434d-ac0a-29f5c97c9991'); add: (#label->'Metadata'); add: (#iconCode->'nil'); add: (#id->#'78daa25d-f902-4123-993c-80d30787981f'); add: (#isReference->false); add: (#viewDefinition->nil); yourself)