steps
step3ec57f85c3f04ae988098352569e3745
	<step>

	^ ((Dictionary new) add: (#definition->#'dd1b9792-357b-452e-8683-40ac6e61457a'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'9 July 2015 2:13:20 am'); yourself)); add: (#isProperty->true); add: (#next->#'8c2a7882-8bc9-44ef-ac46-845264fec325'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'3ec57f85-c3f0-4ae9-8809-8352569e3745'); add: (#isReference->false); add: (#viewDefinition->nil); yourself)