steps
stepsenders
	<step>

	^ ((Dictionary new) add: (#definition->#'4483dde3-686f-4d45-97bb-91c832078bf2'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->ByteSymbol); add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'9 July 2015 1:16:43 am'); add: (#outputKind->MethodReference); add: (#priority->200); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->'Senders'); add: (#iconCode->'nil'); add: (#id->#senders); add: (#isReference->false); add: (#viewDefinition->nil); yourself)