steps
stepf4830bc71e6e4761b74c4f8069f57611
	<step>

	^ ((Dictionary new) add: (#definition->#'69c40406-cd01-45da-864e-6cbd84d38e7b'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'10 July 2015 7:34:40 pm'); add: (#copyOf->#'0f2ca14f-2c24-4b84-96ba-db0918a013b4'); add: (#isNew->false); yourself)); add: (#isProperty->true); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'f4830bc7-1e6e-4761-b74c-4f8069f57611'); add: (#isReference->false); add: (#viewDefinition->nil); yourself)