steps
stepoutline
	<step>

	^ ((Dictionary new) add: (#definition->#'96405165-0157-45ef-aa95-e2bf9745b2e5'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->ClassDescription); add: (#creationTimeStamp->'9 July 2015 1:16:43 am'); add: (#creationAuthor->'cc'); add: (#outputKind->CompiledMethod); add: (#view->ViTreeView); add: (#priority->40); yourself)); add: (#isProperty->false); add: (#next->#'7d87e9d8-d48c-4caf-a57d-d8d11878c0a7'); add: (#label->'Class Outline'); add: (#iconCode->'nil'); add: (#id->#outline); add: (#isReference->false); add: (#viewDefinition->nil); yourself)