steps
step7d87e9d8d48c4cafa57dd8d11878c0a7
	<step>

	^ ((Dictionary new) add: (#definition->#'a27df309-69bd-455e-9eba-1919aad8d519'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'9 July 2015 1:16:43 am'); yourself)); add: (#isProperty->false); add: (#next->#'e7d53167-39e0-4dd7-91a4-ee55c6792709'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'7d87e9d8-d48c-4caf-a57d-d8d11878c0a7'); add: (#isReference->false); add: (#viewDefinition->nil); yourself)