steps
stepformattedQueries
	<step>

	^ ((Dictionary new) add: (#definition->#'bc853fde-e83d-47e0-881c-3ab01fca76de'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->ViQueryStep); add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'9 July 2015 1:16:43 am'); add: (#outputKind->ViQueryStep); yourself)); add: (#isProperty->false); add: (#next->#'bd0f3eb4-8110-4476-87ad-5240aaab3f4c'); add: (#label->'Scripts'); add: (#iconCode->'nil'); add: (#id->#formattedQueries); add: (#isReference->false); add: (#viewDefinition->nil); yourself)