steps
stepf4c63ac0a7ff4da5bee2e3429a6bebc3
	<step>

	^ ((Dictionary new) add: (#definition->#'259a8a10-dca7-4e70-9e10-4d32b00419b4'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'9 July 2015 3:43:19 am'); yourself)); add: (#isProperty->false); add: (#next->#'bc0000b3-bcd1-4dc6-9bd7-a342421895f9'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'f4c63ac0-a7ff-4da5-bee2-e3429a6bebc3'); add: (#isReference->false); add: (#viewDefinition->nil); yourself)