steps
step09dc2d897271447a9a88db3f4750d7fa
	<step>

	^ ((Dictionary new) add: (#definition->#'690791e0-2474-4f72-9e51-d9c7ceb8e09d'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->PackageInfo); add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'9 July 2015 1:16:43 am'); add: (#outputKind->ClassDescription); add: (#view->ViTreeView); add: (#priority->100); yourself)); add: (#isProperty->false); add: (#next->#'ff6e51e8-bc1b-46f5-a080-851208e69747'); add: (#label->'Package Outline'); add: (#iconCode->'nil'); add: (#id->#'09dc2d89-7271-447a-9a88-db3f4750d7fa'); add: (#isReference->false); add: (#viewDefinition->nil); yourself)