steps
stepa5f038f9ce624f28a31794215873024a
	<step>

	^ ((Dictionary new) add: (#definition->#'62a15092-ed59-459e-8dc8-72b7378882cd'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'10 July 2015 7:33:09 pm'); add: (#copyOf->#'5344d438-2c05-40e6-9827-54f91c001fa5'); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->#'81782998-a7a4-42a0-8200-0c995d811e2f'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'a5f038f9-ce62-4f28-a317-94215873024a'); add: (#isReference->false); add: (#viewDefinition->nil); yourself)