steps
stepartifacts
	<step>

	^ ((Dictionary new) add: (#definition->#'f155b5ff-6526-480e-b9ba-9ab54a45f662'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'cc'); add: (#view->ViArtifactListView2); add: (#creationTimeStamp->'9 July 2015 1:16:43 am'); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->'Artifacts'); add: (#iconCode->'nil'); add: (#id->#artifacts); add: (#isReference->false); add: (#viewDefinition->nil); yourself)