steps
stepc1bcb1056b34434dac0a29f5c97c9991
	<step>

	^ ((Dictionary new) add: (#definition->#'5f3a4d16-4e03-492e-a383-75c8bdbfa0fe'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'10 July 2015 10:25:09 am'); yourself)); add: (#isProperty->true); add: (#next->#'0f2ca14f-2c24-4b84-96ba-db0918a013b4'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'c1bcb105-6b34-434d-ac0a-29f5c97c9991'); add: (#isReference->false); add: (#viewDefinition->nil); yourself)