steps
stepf99d4fd13d69436f8e2be897e450b2f8
	<step>

	^ ((Dictionary new) add: (#definition->#'cfb46d54-e210-47fa-b91c-c09e66b50b23'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'9 July 2015 3:02:22 am'); yourself)); add: (#isProperty->false); add: (#next->#'5344d438-2c05-40e6-9827-54f91c001fa5'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'f99d4fd1-3d69-436f-8e2b-e897e450b2f8'); add: (#isReference->false); add: (#viewDefinition->nil); yourself)