steps
step83d4711f0e2a4b22859878572003dc6b
	<step>

	^ ((Dictionary new) add: (#definition->#'59c7c2bc-ce29-4d31-a1d4-2da5a1e8745d'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'10 July 2015 7:33:09 pm'); add: (#copyOf->#'9de447b3-fe9b-4620-8ab5-488f6cf9f89e'); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->#'e88502ff-0f4e-4238-b242-06630d4113fe'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'83d4711f-0e2a-4b22-8598-78572003dc6b'); add: (#isReference->false); add: (#viewDefinition->nil); yourself)