steps
stepb5752cd9ddb54a5abfd22d96b61fdeb7
	<step>

	^ ((Dictionary new) add: (#definition->#'a24fdefd-9f05-4377-bfd6-21d95f9ddd8e'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'10 July 2015 7:33:09 pm'); add: (#copyOf->#'8c2a7882-8bc9-44ef-ac46-845264fec325'); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->#'f99d4fd1-3d69-436f-8e2b-e897e450b2f8'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'b5752cd9-ddb5-4a5a-bfd2-2d96b61fdeb7'); add: (#isReference->false); add: (#viewDefinition->nil); yourself)