steps
step0f2ca14f2c244b8496badb0918a013b4
	<step>

	^ ((Dictionary new) add: (#definition->#'581b90b1-66cb-4ad6-89f7-72f20a7e4b6e'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'10 July 2015 10:25:41 am'); yourself)); add: (#isProperty->true); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'0f2ca14f-2c24-4b84-96ba-db0918a013b4'); add: (#isReference->false); add: (#viewDefinition->nil); yourself)