steps
step5344d4382c0540e6982754f91c001fa5
	<step>

	^ ((Dictionary new) add: (#definition->#'08eba525-fadd-47a1-9441-91b4ae250cf3'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'9 July 2015 2:42:35 am'); yourself)); add: (#isProperty->false); add: (#next->#'ee67a9b0-655e-46a5-a29f-b524f1478328'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'5344d438-2c05-40e6-9827-54f91c001fa5'); add: (#isReference->false); add: (#viewDefinition->nil); yourself)