steps
step8c2a78828bc944efac46845264fec325
	<step>

	^ ((Dictionary new) add: (#definition->#'3259496b-af05-4b57-b99f-1cd654104a41'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'9 July 2015 2:14:15 am'); yourself)); add: (#isProperty->false); add: (#next->#'f99d4fd1-3d69-436f-8e2b-e897e450b2f8'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'8c2a7882-8bc9-44ef-ac46-845264fec325'); add: (#isReference->false); add: (#viewDefinition->nil); yourself)