steps
step883221bbef004a3c99205b5667512d8e
	<step>

	^ ((Dictionary new) add: (#definition->#'81424701-7382-4a7f-9646-793417d10ba4'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'cc'); add: (#view->ViMultiPaneWidget); add: (#creationTimeStamp->'10 July 2015 7:34:01 pm'); add: (#isNew->false); add: (#optimalExtent->(930@398)); yourself)); add: (#isProperty->true); add: (#next->#'5daa0ebc-efa4-48a6-be41-1121738da03b'); add: (#label->'CCMail'); add: (#iconCode->'nil'); add: (#id->#'883221bb-ef00-4a3c-9920-5b5667512d8e'); add: (#isReference->false); add: (#viewDefinition->nil); yourself)