steps
stepee67a9b0655e46a5a29fb524f1478328
	<step>

	^ ((Dictionary new) add: (#definition->#'73e4dc96-2f44-451e-bf4e-d8ba125ce5e6'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#isNew->false); add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'9 July 2015 2:57:36 am'); yourself)); add: (#isProperty->true); add: (#next->#'9de447b3-fe9b-4620-8ab5-488f6cf9f89e'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'ee67a9b0-655e-46a5-a29f-b524f1478328'); add: (#isReference->false); add: (#viewDefinition->nil); yourself)