definitions
def0b4447fb7ebb4e70a4727e95ba293f46
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'9 July 2015 1:16:43 am'); yourself)); add: (#id->#'0b4447fb-7ebb-4e70-a472-7e95ba293f46'); add: (#block->[:in :out | [#groups] value in: [:result |
	out addAll: result asList]]); add: (#sourceCode->'[:in :out | [#groups] value in: [:result |
	out addAll: result asList]]'); yourself)