definitions
def4dbf1795b7924f92970872fcb74b96c9
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'9 July 2015 1:16:43 am'); yourself)); add: (#id->#'4dbf1795-b792-4f92-9708-72fcb74b96c9'); add: (#block->[:in :out | out addAll: ([:classes | classes
		sorted: [:c1 :c2 | c1 name <= c2 name]] value: in)]); add: (#sourceCode->'[:in :out | out addAll: ([:classes | classes
		sorted: [:c1 :c2 | c1 name <= c2 name]] value: in)]'); yourself)