definitions
def8142470173824a7f9646793417d10ba4
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'10 July 2015 7:34:01 pm'); yourself)); add: (#id->#'81424701-7382-4a7f-9646-793417d10ba4'); add: (#block->[:in :out | out add: {#objects -> in}, [{
	#bounds -> (1@0 corner: 340@500).
	#current -> #'942ba1de-1098-4cb4-8300-43e117f95666'.
	#id -> #'3770640e-e2df-4628-98bb-66612873bb69'.
	#out -> #(#(#interactive #'36243f2b-ee57-4691-8fa1-cc6d867e3f10' ) #(#interactive #'6e86ed4c-9dfa-4314-862b-b54c599271ca' ) ).
	#in -> #(#(#automatic #outer ) ).
}] value]); add: (#sourceCode->'[:in :out | out add: {#objects -> in}, [{
	#bounds -> (1@0 corner: 340@500).
	#current -> #''942ba1de-1098-4cb4-8300-43e117f95666''.
	#id -> #''3770640e-e2df-4628-98bb-66612873bb69''.
	#out -> #(#(#interactive #''36243f2b-ee57-4691-8fa1-cc6d867e3f10'' ) #(#interactive #''6e86ed4c-9dfa-4314-862b-b54c599271ca'' ) ).
	#in -> #(#(#automatic #outer ) ).
}] value]'); yourself)