definitions
def9020d2b3f8204d7e9649b747388cd016
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'9 July 2015 1:16:43 am'); yourself)); add: (#id->#'9020d2b3-f820-4d7e-9649-b747388cd016'); add: (#block->[:in :out | [#groups] value in: [:result |
	out addAll: result asList]]); add: (#sourceCode->'[:in :out | [#groups] value in: [:result |
	out addAll: result asList]]'); yourself)