definitions
defc32f87c61c0946e78d62a12f4f0badf1
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'9 July 2015 1:16:43 am'); yourself)); add: (#id->#'c32f87c6-1c09-46e7-8d62-a12f4f0badf1'); add: (#block->[:in :out | out addAll: ([:tuples | tuples asGroups] value: in)]); add: (#sourceCode->'[:in :out | out addAll: ([:tuples | tuples asGroups] value: in)]'); yourself)