definitions
defd2887e95d205424dbba13ede04d1211e
	<definition>

	^ ((Dictionary new) add: (#class->ViQueryStepDefinition); add: (#properties->((Dictionary new) add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'10 July 2015 7:34:02 pm'); yourself)); add: (#id->#'d2887e95-d205-424d-bba1-3ede04d1211e'); add: (#block->[:in :out | out add: {#objects -> in}, [{
	#bounds -> (345@90 corner: 763@500).
	#current -> #'fac0a138-6194-43a5-b706-c0103b6b912f'.
	#id -> #'6e86ed4c-9dfa-4314-862b-b54c599271ca'.
	#out -> #().
	#in -> #(#(#interactive #'3770640e-e2df-4628-98bb-66612873bb69' ) ).
}] value]); add: (#sourceCode->'[:in :out | out add: {#objects -> in}, [{
	#bounds -> (345@90 corner: 763@500).
	#current -> #''fac0a138-6194-43a5-b706-c0103b6b912f''.
	#id -> #''6e86ed4c-9dfa-4314-862b-b54c599271ca''.
	#out -> #().
	#in -> #(#(#interactive #''3770640e-e2df-4628-98bb-66612873bb69'' ) ).
}] value]'); yourself)