steps
stepdefaultProperties
	<step>

	^ ((Dictionary new) add: (#definition->#'3de6a61f-8fcc-4ab7-89e2-8e85769f95b3'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'9 July 2015 1:16:43 am'); yourself)); add: (#isProperty->true); add: (#next->#'5e47068e-8090-4506-b98a-3fe787062073'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#defaultProperties); add: (#isReference->false); add: (#viewDefinition->nil); yourself)