steps
step5daa0ebcefa448a6be411121738da03b
	<step>

	^ ((Dictionary new) add: (#definition->#'d2887e95-d205-424d-bba1-3ede04d1211e'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'cc'); add: (#view->ViMultiPaneWidget); add: (#creationTimeStamp->'10 July 2015 7:34:02 pm'); add: (#isNew->false); yourself)); add: (#isProperty->true); add: (#next->#'2e98d65a-3dcd-4f52-a07d-46bf5bdf38e5'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'5daa0ebc-efa4-48a6-be41-1121738da03b'); add: (#isReference->false); add: (#viewDefinition->nil); yourself)