steps
step942ba1de10984cb4830043e117f95666
	<step>

	^ ((Dictionary new) add: (#definition->#'7d8e47d4-6c15-4d72-9250-fac11d21cc1b'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->MailArchive); add: (#creationTimeStamp->'10 July 2015 7:33:09 pm'); add: (#view->ViTreeViewExtended); add: (#creationAuthor->'cc'); add: (#copyOf->#'ad47d780-cb65-42e5-8cdf-17110bdc4f09'); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->#'b0a7189c-df47-4775-802e-247f2e3775a5'); add: (#label->'Inboxes'); add: (#iconCode->'nil'); add: (#id->#'942ba1de-1098-4cb4-8300-43e117f95666'); add: (#isReference->false); add: (#viewDefinition->nil); yourself)