steps
step1e65b4c673924e91bb68091b2bb67736
	<step>

	^ ((Dictionary new) add: (#definition->#'a353392d-c4c6-45e7-9fbd-246cb61b0121'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'9 July 2015 1:16:43 am'); yourself)); add: (#isProperty->false); add: (#next->#'c4dde508-41f3-4be4-aa10-6b3535c7d4e4'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'1e65b4c6-7392-4e91-bb68-091b2bb67736'); add: (#isReference->false); add: (#viewDefinition->nil); yourself)