steps
stepc1d85e7c8bf446afa27a1bcce4246347
	<step>

	^ ((Dictionary new) add: (#definition->#'9020d2b3-f820-4d7e-9649-b747388cd016'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'9 July 2015 1:16:43 am'); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'c1d85e7c-8bf4-46af-a27a-1bcce4246347'); add: (#isReference->true); add: (#viewDefinition->nil); yourself)