steps
stepf99d4fd13d69436f8e2be897e450b2f8
	<step>

	^ ((Dictionary new) add: (#definition->#'77f7e8b4-c55d-42a7-89b5-7a444470fbd7'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'10 July 2015 7:33:09 pm'); add: (#copyOf->#'f99d4fd1-3d69-436f-8e2b-e897e450b2f8'); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->#'a5f038f9-ce62-4f28-a317-94215873024a'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'f99d4fd1-3d69-436f-8e2b-e897e450b2f8'); add: (#isReference->false); add: (#viewDefinition->nil); yourself)