steps
step06f4ea1c103848a6bacf14a7b3a4ee01
	<step>

	^ ((Dictionary new) add: (#definition->#'ea49fc4b-3ac2-470f-a1dc-8a7a28e2d8fa'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'10 July 2015 7:34:01 pm'); add: (#copyOf->#'bc0000b3-bcd1-4dc6-9bd7-a342421895f9'); add: (#isNew->false); yourself)); add: (#isProperty->true); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'06f4ea1c-1038-48a6-bacf-14a7b3a4ee01'); add: (#isReference->false); add: (#viewDefinition->nil); yourself)