steps
step2e98d65a3dcd4f52a07d46bf5bdf38e5
	<step>

	^ ((Dictionary new) add: (#definition->#'4cd61f7f-e47b-48af-b566-35d05b819806'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'cc'); add: (#view->ViMultiPaneWidget); add: (#creationTimeStamp->'10 July 2015 7:34:45 pm'); add: (#isNew->false); yourself)); add: (#isProperty->true); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'2e98d65a-3dcd-4f52-a07d-46bf5bdf38e5'); add: (#isReference->false); add: (#viewDefinition->nil); yourself)