steps
stepc3039d39251041529c9c2063276b026b
	<step>

	^ ((Dictionary new) add: (#definition->#'3d0d9a96-08af-4f3e-967a-8f8136b8b2aa'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputKind->MailArchiveEntry); add: (#creationTimeStamp->'10 July 2015 7:34:40 pm'); add: (#view->ViTableView); add: (#creationAuthor->'cc'); add: (#copyOf->#'78daa25d-f902-4123-993c-80d30787981f'); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->#'d08073e6-6564-49ef-ab2e-f62d10e57cc1'); add: (#label->'Metadata'); add: (#iconCode->'nil'); add: (#id->#'c3039d39-2510-4152-9c9c-2063276b026b'); add: (#isReference->false); add: (#viewDefinition->nil); yourself)