steps
stepbf497c9e78924e34a327d75650fdf5d3
	<step>

	^ ((Dictionary new) add: (#definition->#'5f8b0880-52d0-40a3-83c9-0e93711b3495'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'9 July 2015 1:16:43 am'); yourself)); add: (#isProperty->false); add: (#next->#'c6e38073-5eed-4a37-80d5-0308efa9086f'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'bf497c9e-7892-4e34-a327-d75650fdf5d3'); add: (#isReference->false); add: (#viewDefinition->nil); yourself)