steps
stepc6e380735eed4a3780d50308efa9086f
	<step>

	^ ((Dictionary new) add: (#definition->#'0d7ca75d-2f63-448f-9b4e-1b05d3c55bcb'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'9 July 2015 1:16:43 am'); yourself)); add: (#isProperty->false); add: (#next->#'1e65b4c6-7392-4e91-bb68-091b2bb67736'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'c6e38073-5eed-4a37-80d5-0308efa9086f'); add: (#isReference->false); add: (#viewDefinition->nil); yourself)