steps
step5e7d06c65da44bee89990f4029b9306b
	<step>

	^ ((Dictionary new) add: (#definition->#'6d90480b-9ebd-41b2-a303-c9d54d0e1fa7'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'9 July 2015 1:16:43 am'); yourself)); add: (#isProperty->true); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'5e7d06c6-5da4-4bee-8999-0f4029b9306b'); add: (#isReference->false); add: (#viewDefinition->nil); yourself)