steps
step85abea9727ad4117951a35dc56936566
	<step>

	^ ((Dictionary new) add: (#definition->#'0b4447fb-7ebb-4e70-a472-7e95ba293f46'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'9 July 2015 1:16:43 am'); yourself)); add: (#isProperty->false); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'85abea97-27ad-4117-951a-35dc56936566'); add: (#isReference->true); add: (#viewDefinition->nil); yourself)