steps
stepe7d5316739e04dd791a4ee55c6792709
	<step>

	^ ((Dictionary new) add: (#definition->#'8dee0187-b791-483a-b21b-a28a4f1d3d51'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'9 July 2015 1:16:43 am'); yourself)); add: (#isProperty->false); add: (#next->#'85abea97-27ad-4117-951a-35dc56936566'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'e7d53167-39e0-4dd7-91a4-ee55c6792709'); add: (#isReference->false); add: (#viewDefinition->nil); yourself)