steps
step1de794035bd2405b877d97a5f88bb7a6
	<step>

	^ ((Dictionary new) add: (#definition->#'fade23d3-3752-4012-bd02-6e89a2f247a8'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'9 July 2015 1:16:43 am'); yourself)); add: (#isProperty->true); add: (#next->nil); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'1de79403-5bd2-405b-877d-97a5f88bb7a6'); add: (#isReference->false); add: (#viewDefinition->nil); yourself)