steps
stepfac0a138619443a5b706c0103b6b912f
	<step>

	^ ((Dictionary new) add: (#definition->#'567973e2-275f-4d5b-9884-9ec8b861a8a8'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#inputType->MailArchiveEntry); add: (#view->ViTextView); add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'10 July 2015 7:34:01 pm'); add: (#copyOf->#'09a70550-8f75-40a1-91f8-f76f6f74c232'); add: (#isNew->false); yourself)); add: (#isProperty->false); add: (#next->#'047ec1c8-2578-4b3f-8a99-3d2670fd42ec'); add: (#label->'Message'); add: (#iconCode->'nil'); add: (#id->#'fac0a138-6194-43a5-b706-c0103b6b912f'); add: (#isReference->false); add: (#viewDefinition->nil); yourself)