steps
stepbd0f3eb48110447687ad5240aaab3f4c
	<step>

	^ ((Dictionary new) add: (#definition->#'927af6c1-aff4-4eed-a45f-b6bf3aa714bd'); add: (#class->ViScriptPart); add: (#properties->((Dictionary new) add: (#creationAuthor->'cc'); add: (#creationTimeStamp->'9 July 2015 1:16:43 am'); yourself)); add: (#isProperty->true); add: (#next->#'5e7d06c6-5da4-4bee-8999-0f4029b9306b'); add: (#label->nil); add: (#iconCode->'nil'); add: (#id->#'bd0f3eb4-8110-4476-87ad-5240aaab3f4c'); add: (#isReference->false); add: (#viewDefinition->nil); yourself)